# Generated by Django 6.0.1 on 2026-06-09 20:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xof_per_ngn', models.DecimalField(decimal_places=6, default=Decimal('0.385000'), max_digits=12)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'taux de change',
                'verbose_name_plural': 'taux de change',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=10)),
                ('event', models.CharField(blank=True, max_length=60)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'log webhook',
                'verbose_name_plural': 'logs webhooks',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('XOF', 'FCFA (XOF)'), ('NGN', 'Naira (NGN)')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('provider', models.CharField(choices=[('paydunya', 'PayDunya'), ('paystack', 'Paystack')], max_length=10)),
                ('operator', models.CharField(blank=True, max_length=20)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('provider_token', models.CharField(blank=True, max_length=255)),
                ('checkout_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Confirmé'), ('failed', 'Échoué')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dépôt',
                'verbose_name_plural': 'dépôts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('XOF', 'FCFA (XOF)'), ('NGN', 'Naira (NGN)')], max_length=3)),
                ('to_currency', models.CharField(choices=[('XOF', 'FCFA (XOF)'), ('NGN', 'Naira (NGN)')], max_length=3)),
                ('amount_from', models.DecimalField(decimal_places=2, max_digits=16)),
                ('rate_used', models.DecimalField(decimal_places=6, max_digits=12)),
                ('fee_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount_to', models.DecimalField(decimal_places=2, max_digits=16)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'échange',
                'verbose_name_plural': 'échanges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('XOF', 'FCFA (XOF)'), ('NGN', 'Naira (NGN)')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('operator', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bank_code', models.CharField(blank=True, max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=80)),
                ('account_number', models.CharField(blank=True, max_length=10)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Payé'), ('failed', 'Échoué')], default='pending', max_length=12)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.beneficiary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'retrait',
                'verbose_name_plural': 'retraits',
                'ordering': ['-created_at'],
            },
        ),
    ]
