# Generated by Django 6.0.1 on 2026-06-09 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='provider',
            field=models.CharField(choices=[('paydunya', 'PayDunya'), ('fedapay', 'FedaPay'), ('paystack', 'Paystack')], max_length=10),
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('XOF', 'FCFA (XOF)'), ('NGN', 'Naira (NGN)')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('note', models.CharField(blank=True, max_length=140, verbose_name='note')),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transfert interne',
                'verbose_name_plural': 'transferts internes',
                'ordering': ['-created_at'],
            },
        ),
    ]
