# Generated by Django 6.0.1 on 2026-06-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
