# Generated by Django 6.0.1 on 2026-06-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_pin_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='GoChange', max_length=40)),
                ('tagline', models.CharField(blank=True, default='Envoyez vos Naira, recevez du FCFA.', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#0066FF', help_text='Couleur principale (hex), ex. #0066FF', max_length=7)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'réglages du site',
                'verbose_name_plural': 'réglages du site',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
    ]
