# Generated by Django 6.0.1 on 2026-06-09 20:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('momo', 'Mobile Money (XOF)'), ('bank', 'Compte bancaire (NGN)')], max_length=4)),
                ('label', models.CharField(blank=True, max_length=80, verbose_name='libellé')),
                ('operator', models.CharField(blank=True, choices=[('mtn', 'MTN MoMo'), ('moov', 'Moov Money'), ('celtiis', 'Celtiis Cash')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bank_code', models.CharField(blank=True, max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=80)),
                ('account_number', models.CharField(blank=True, max_length=10)),
                ('account_name', models.CharField(blank=True, max_length=120, verbose_name='nom du titulaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bénéficiaire',
                'verbose_name_plural': 'bénéficiaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_ngn', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('balance_xof', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'portefeuille',
                'verbose_name_plural': 'portefeuilles',
            },
        ),
    ]
